### ISSUE TITLE
Badge is not displaying for some android devices

### ISSUE THREAD

**Issue by jitendrapal00** [katzer/cordova-plugin-badge#111]
I am using Cordova-plugin-badge into our ionic3 app. it is working fine on some devices but for some android devices like Samsung, Gionee etc. it is not working(i mean the badge is not displaying on main app icon).
So Please let me know how we can resolve this issues.

**Comment by katzer** [comment]
@jitendrapal00 I've made some commits to improve the situation.

1. `isSupported` method to check at runtime if its possible to apply badges on Android. For other platforms it will always return _true_. Since the internal lib method is doing some more init stuff this might resolve the issue where the plugin could not apply a badge while the _IsBadgeWorkingApp_ worked properly.
2. Upgraded to latest version `ShortcutBadge@1.1.21`
3. The `appShortcutBadgerCustom` flag allows to integrate ShortcutBadger other then the default way. Like a sub project for example so its easier to debug the external code.

In case of Samsung ShortcutBadges uses the DefaultBadger for `SDK_VERSION >= 21`. You could comment out the [switch](https://github.com/leolin310148/ShortcutBadger/blob/c072debd0719578d3d301648f4642bae1df3716c/ShortcutBadger/src/main/java/me/leolin/shortcutbadger/impl/SamsungHomeBadger.java#L35) to always use the implementation for Samsung. By looking through some tickets others have done the same with success.
