### ISSUE TITLE
Phonegap remote build failed

### ISSUE THREAD

**Issue by GiladAdar** [katzer/cordova-plugin-badge#61]
Hi,
This plugin is not working on android, i am using phonegap remote build
`<plugin name="cordova-plugin-badge" spec="0.7.2" source="npm" />`
and this one is not working on ios and android:
`<gap:plugin name="de.appplant.cordova.plugin.badge" version="0.7.2" source="npm" />`

any idea? Thanks.

**Comment by badpenguin** [comment]
+1

**Comment by easedu** [comment]
+1

**Comment by rodrigo01** [comment]
this works fine, some Android Version dont show the number badge, but i dont know why this show a simple local alert

**Comment by mlabarca** [comment]
+1, though the build itself doesn't fail for me, it just doesn't work.  When building remotely with `<plugin name="cordova-plugin-badge" spec="0.7.2" source="npm" />` The build doesn't fail like in https://github.com/katzer/cordova-plugin-badge/issues/68, but after building the notifications plugin namespace isn't defined (`cordova.plugins.notifications`) This is probably unrelated because since v0.70 android requires cordova 4.0 which isn't my case yet. (Is this documented btw? maybe I can submit a PR for the wiki later)

Remote build works fine in my old version of cordova when using a much older plugin version through pgb: 
 `<plugin name="de.appplant.cordova.plugin.badge" spec="0.6.4" source="pgb" />` But since i'd really like the extra compatibility for android added on v0.7.1 I'll just hold off until I upgrade to v4.

**Comment by mlabarca** [comment]
Nevermind. Shortcut badger changed something in the way dependencies are handled and build is failing for cordova-plugin-badge @ 0.7.2 . Will open a separate issue.
