### ISSUE TITLE
badge does nothing on Android (6.0.1)

### ISSUE THREAD

**Issue by jeffthompson1971** [katzer/cordova-plugin-badge#69]
Of course I make the check to see if badging is allowed and it returns 'true' for me.  Same code works just fine on IOS but on my Android just doesn't work at all - shows nothing on my icon.   

It it a Marshmallow thing?  If so when will Marshmallow be supported for badging?

**Comment by Yagger** [comment]
Same here

**Comment by slorber** [comment]
as far as I undertand, this lib depends on [me.leolin:ShortcutBadger:1.1.4@aar](https://github.com/leolin310148/ShortcutBadger) which means it's likely to only work on devices that ShortcutBadger support.

According to this [comment](https://github.com/phonegap/phonegap-plugin-push/issues/190#issuecomment-229678121) it seems that stock Android (ie Nexus 5X / 6P etc) are not supported by ShortcutBadger and will probably not because Google does not permit it. It's likely that you run a 6.x Android version on a stock Android, as far as I know not much vendors have upgraded yet to 6.x. For me it's not a 6.x problem but more related to missing support for Google phones.

**Comment by itemir** [comment]
Thanks @slorber, this explains it. #74 and #75 are likely related to this as well.

**Comment by katzer** [comment]
As @slorber explained correctly it all depends on ShortcutBadger lib. At least I will upgrade the lib to ues the latest version.

**Comment by slorber** [comment]
for the record, after upgrading my Samsung A6 2015 to Android 6.0, I still have the badge working
